package consolizer

import (
	"fmt"
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestPrintDialogWithTextStyles(test *testing.T) {
	commonResource.isDebugEnabled = true
	layerWidth := 40
	layerHeight := 10
	textStyleAlias := "redColor"
	InitializeTerminal(layerWidth, layerHeight)
	layerAlias1 := AddLayer(0, 0, layerWidth, layerHeight, 1, nil)
	Layer(layerAlias1)
	Color(4, 6)
	layerAlias1.FillLayer("a1a2a3a4a5")
	Color(8, 9)
	attributeEntry := NewTextStyle()
	attributeEntry.ForegroundColor = GetRGBColor(255, 0, 0)
	AddTextStyle(textStyleAlias, attributeEntry)
	stringToPrint := "This is a {{redColor}}sample{{/}} line of text. This line will {{redColor}}automatically{{/}} wrap without cutting words."
	layerAlias1.PrintDialog(2, 2, 20, 0, false, stringToPrint)
	UpdateDisplay(false)
	layerEntry := commonResource.screenLayer
	obtainedValue := layerEntry.GetBasicAnsiStringAsBase64()
	expectedValue := "G1szODsyOzA7MDsxMjhtG1s0ODsyOzA7MTI4OzEyOG1hMWEyYTNhNGE1YTFhMmEzYTRhNWExYTJhM2E0YTVhMWEyYTNhNGE1G1szODsyOzA7MDswbRtbNDg7MjswOzA7MG0KG1szODsyOzA7MDsxMjhtG1s0ODsyOzA7MTI4OzEyOG1hMWEyYTNhNGE1YTFhMmEzYTRhNWExYTJhM2E0YTVhMWEyYTNhNGE1G1szODsyOzA7MDswbRtbNDg7MjswOzA7MG0KG1szODsyOzA7MDsxMjhtG1s0ODsyOzA7MTI4OzEyOG1hMRtbMzg7MjsxMjg7MTI4OzEyOG0bWzQ4OzI7MjU1OzA7MG1UaGlzIGlzIGEgG1szODsyOzI1NTswOzBtG1s0ODsyOzA7MDswbXNhbXBsZRtbMzg7MjswOzA7MTI4bRtbNDg7MjswOzEyODsxMjhtYTVhMWEyYTNhNGE1YTFhMmEzYTRhNRtbMzg7MjswOzA7MG0bWzQ4OzI7MDswOzBtChtbMzg7MjswOzA7MTI4bRtbNDg7MjswOzEyODsxMjhtYTEbWzM4OzI7MTI4OzEyODsxMjhtG1s0ODsyOzI1NTswOzBtbGluZSBvZiB0ZXh0LiBUaGlzG1szODsyOzA7MDsxMjhtG1s0ODsyOzA7MTI4OzEyOG1hMWEyYTNhNGE1YTFhMmEzYTRhNRtbMzg7MjswOzA7MG0bWzQ4OzI7MDswOzBtChtbMzg7MjswOzA7MTI4bRtbNDg7MjswOzEyODsxMjhtYTEbWzM4OzI7MTI4OzEyODsxMjhtG1s0ODsyOzI1NTswOzBtbGluZSB3aWxsG1szODsyOzA7MDsxMjhtG1s0ODsyOzA7MTI4OzEyOG0xYTJhM2E0YTVhMWEyYTNhNGE1YTFhMmEzYTRhNRtbMzg7MjswOzA7MG0bWzQ4OzI7MDswOzBtChtbMzg7MjswOzA7MTI4bRtbNDg7MjswOzEyODsxMjhtYTEbWzM4OzI7MjU1OzA7MG0bWzQ4OzI7MDswOzBtYXV0b21hdGljYWxseRtbMzg7MjsxMjg7MTI4OzEyOG0bWzQ4OzI7MjU1OzA7MG0gd3JhcBtbMzg7MjswOzA7MTI4bRtbNDg7MjswOzEyODsxMjhtYTFhMmEzYTRhNWExYTJhM2E0YTUbWzM4OzI7MDswOzBtG1s0ODsyOzA7MDswbQobWzM4OzI7MDswOzEyOG0bWzQ4OzI7MDsxMjg7MTI4bWExG1szODsyOzEyODsxMjg7MTI4bRtbNDg7MjsyNTU7MDswbXdpdGhvdXQgY3V0dGluZxtbMzg7MjswOzA7MTI4bRtbNDg7MjswOzEyODsxMjhtNGE1YTFhMmEzYTRhNWExYTJhM2E0YTUbWzM4OzI7MDswOzBtG1s0ODsyOzA7MDswbQobWzM4OzI7MDswOzEyOG0bWzQ4OzI7MDsxMjg7MTI4bWExG1szODsyOzEyODsxMjg7MTI4bRtbNDg7MjsyNTU7MDswbXdvcmRzLhtbMzg7MjswOzA7MTI4bRtbNDg7MjswOzEyODsxMjhtYTVhMWEyYTNhNGE1YTFhMmEzYTRhNWExYTJhM2E0YTUbWzM4OzI7MDswOzBtG1s0ODsyOzA7MDswbQobWzM4OzI7MDswOzEyOG0bWzQ4OzI7MDsxMjg7MTI4bWExYTJhM2E0YTVhMWEyYTNhNGE1YTFhMmEzYTRhNWExYTJhM2E0YTUbWzM4OzI7MDswOzBtG1s0ODsyOzA7MDswbQobWzM4OzI7MDswOzEyOG0bWzQ4OzI7MDsxMjg7MTI4bWExYTJhM2E0YTVhMWEyYTNhNGE1YTFhMmEzYTRhNWExYTJhM2E0YTUbWzM4OzI7MDswOzBtG1s0ODsyOzA7MDswbQo="
	obtainedValueBase64 := layerEntry.GetAnsiStringFromBase64(obtainedValue)
	expectedValueBase64 := layerEntry.GetAnsiStringFromBase64(expectedValue)
	if !assert.Equalf(test, expectedValue, obtainedValue, "The updated screen does not match the master original!") {
		fmt.Println("Expected:\n", expectedValueBase64)
		fmt.Println("Obtained:\n", obtainedValueBase64)
	}
}
